sudo: required
language: bash
services: 
  - docker

before_install:
  - git clone https://github.com/chrishasl/obsidian-qt-docker odn-qt-wallet
  - docker build -t odn-qt-wallet .
  - docker run --rm -d -v ~/odn-wallet/wallet.dat:/root/.obsidian/wallet.dat --name=odn-qt-wallet odn-qt-wallet

script:
  - docker version
  - docker ps
  - docker ps -a
  - docker exec
  - docker exec odn-qt-wallet w
  - docker exec odn-qt-wallet obsidiand getstakinginfo
