sudo: required
language: bash
services: 
  - docker

before_install:
  - git clone https://github.com/chrishasl/obsidian-qt-docker odn-qt-wallet
  - docker build -t odn-qt-wallet .
  - docker run --privileged --rm -d -v ~/odn-wallet/:/root/.obsidian/ --name=odn-qt-wallet odn-qt-wallet

script:
  - sleep 10
  - docker run --rm -d -v ~/odn-wallet/wallet.dat:/root/.obsidian/wallet.dat --name=odn-qt-wallet odn-qt-wallet
  - docker ps
  - docker ps -a
  - docker exec -ti odn-qt-wallet w
  - docker exec odn-qt-wallet obsidiand getstakinginfo

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
