sudo: required
language: bash
services: 
  - docker

before_install:
  - git clone https://github.com/chrishasl/obsidiand-docker obsidiand-docker
  - docker build -t obsidiand-docker .
  - docker run --privileged --rm -d -v ~/odn-wallet/:/root/.obsidian/ --name=obsidiand-docker obsidiand-docker

script:
  - sleep 10
  - docker run --rm -d -v ~/odn-wallet/wallet.dat:/root/.obsidian/wallet.dat --name=obsidiand-docker obsidiand-docker
  - docker ps
  - docker ps -a
  - docker exec -ti obsidiand-docker w
  - docker exec obsidiand-docker obsidiand getstakinginfo

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
